### ISSUE TITLE
modifier le paramètre de renvoie du getId

### ISSUE THREAD

**Issue by Vautrinss** [bastienricoeur/graphJava#4]

**Comment by Vautrinss** [comment]
il faut modifier le paramètre de renvoie du getId du vertex, il faut renvoyer un int;

**Comment by bastienricoeur** [comment]
J'ai nommé ma variable avec un mauvais nom c'est pas id mais plutôt des informations sur le sommet. Et le prof veut que cette info soit du type objet. Je viens de changer le graph.jar avec la variable nommée différemment.
